exports.scr_content = ''
+'		function inputUpdate(n){'
+'			document.getElementsByName("value_number")[0].value=abits[n].dogovor;'
+'			document.getElementsByName("full_name")[0].value=abits[n].fio;'
+'			document.getElementsByName("year")[0].value = abits[n].srok;'
+'			document.getElementsByName("passport_ser")[0].value = abits[n].serial;'
+'			document.getElementsByName("passport_num")[0].value = abits[n].number;'
+'			document.getElementsByName("passport_who")[0].value = abits[n].vydan;'
+'			document.getElementsByName("passport_when")[0].value = abits[n].data_vyd;'
+'			document.getElementsByName("passport_qcode")[0].value = abits[n].code_podrazd;'
+'			document.getElementsByName("passport_address")[0].value = abits[n].adres_reg;'
+'			document.getElementsByName("student_phone")[0].value = abits[n].tel;'
+'			document.getElementsByName("bablo_sem")[0].value = abits[n].n_sem_oplaty;'
+'			document.getElementsByName("group")[0].value = abits[n].group_n;'
+'			document.getElementsByName("kaf")[0].options[abits[n].speciality].selected = true;'
+'			document.getElementsByName("full_name_zak")[0].value = abits[n].fio_zak;'
+'			document.getElementsByName("passport_ser_zak")[0].value = abits[n].serial_zak;'
+'			document.getElementsByName("passport_num_zak")[0].value = abits[n].number_zak;'
+'			document.getElementsByName("passport_who_zak")[0].value = abits[n].vydan_zak;'
+'			document.getElementsByName("passport_when_zak")[0].value = abits[n].data_vyd_zak;'
+'			document.getElementsByName("passport_address_zak")[0].value = abits[n].adres_reg_zak;'
+'			document.getElementsByName("zak_phone")[0].value = abits[n].tel_zak;'
+'			document.getElementsByName("passport_qcode_zak")[0].value = abits[n].code_podrazd_zak;'

+'		}'

+'		function check(){'
+'			if(!isNaN(parseInt(document.getElementsByName("value_number")[0].value)) && isFinite(document.getElementsByName("value_number")[0].value)){	'	
+'		if(document.getElementsByName("full_name")[0].value&&document.getElementsByName("year")[0].value&&document.getElementsByName("passport_ser")[0].value&&document.getElementsByName("passport_num")[0].value&&document.getElementsByName("passport_who")[0].value&&document.getElementsByName("passport_when")[0].value&&document.getElementsByName("passport_qcode")[0].value&&document.getElementsByName("passport_address")[0].value&&document.getElementsByName("student_phone")[0].value&&document.getElementsByName("bablo_sem")[0].value&&document.getElementsByName("group")[0].value&&document.getElementsByName("full_name_zak")[0].value&&document.getElementsByName("passport_ser_zak")[0].value&&document.getElementsByName("passport_num_zak")[0].value&&document.getElementsByName("passport_who_zak")[0].value&&document.getElementsByName("passport_when_zak")[0].value&&document.getElementsByName("passport_address_zak")[0].value&&document.getElementsByName("zak_phone")[0].value&&document.getElementsByName("passport_qcode_zak")[0].value)'
+'					document.forms[0].submit();'
+'				else{'
+'					document.getElementById("inputErr").style = style="color: red; font-size: 20px; visibility: visible; display: block;";'
+'					document.getElementById("inputErr2").style = style="color: red; font-size: 20px; visibility: visible; display: block;";'
+'				document.getElementsByName("value_number")[0].style="background-color: #fff";'
+'			}}'
+'			else{'
+'				document.getElementsByName("value_number")[0].value="Введите число";'
+'				document.getElementsByName("value_number")[0].style="background-color: #F6C2C2";'
+'			}'
+'		}'
+'function logout(){'
+'	document.cookie = "SSID=none";'
+'	window.location = "/logout";'
+'}';